<?php
declare(strict_types=1);
namespace app\api;
use think\db\exception\DbException;
use think\exception\Handle;
use think\Response;
use Throwable;
class ApiExceptionHandle extends Handle
{
    /**
     * 记录异常信息，日志或其他方式
     * @param Throwable $exception
     */
    public function report(Throwable $exception): void
    {
        parent::report($exception); // TODO: Change the autogenerated stub
    }

    public function render($request, Throwable $e): Response
    {
        // 添加自定义异常处理机制
        if ($e instanceof DbException) {
            return app('json')->fail('数据获取失败', [
                'file' => $e->getFile(),
                'message' => $e->getMessage(),
                'line' => $e->getLine(),
            ]);
        } else {
            return app('json')->fail('系统出现异常', [
                'message' => $e->getMessage(),
                'file' => $e->getFile(),
                'code' => $e->getCode(),
                'line' => $e->getLine(),
                'trace' => $e->getTrace(),
                'previous' => $e->getPrevious(),
            ]);
        }
    }

}
